# ============================================================
# BUILD STAGE
# ============================================================
FROM golang:1.25-alpine AS builder

WORKDIR /app

# Copy dependency files
COPY go.mod go.sum ./

RUN go mod download

# Copy source code
COPY . .

# Build application
RUN CGO_ENABLED=0 GOOS=linux go build \
    -o auth-service \
    ./cmd


# ============================================================
# RUNTIME STAGE
# ============================================================
FROM alpine:3.22

WORKDIR /app

RUN apk --no-cache add ca-certificates

# Copy binary
COPY --from=builder /app/auth-service .

EXPOSE 8080

CMD ["./auth-service"]